name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only --env DATABASE_URL=${{ secrets.DATABASE_URL }}
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
